docker-compose exec mids ab -n 1 -H "Host: user1.comcast.com"  http://localhost:5000/new_user
docker-compose exec mids ab -n 1 -H "Host: user1.comcast.com"  http://localhost:5000/login
docker-compose exec mids ab -n 1 -H "Host: user1.comcast.com"  http://localhost:5000/login0
docker-compose exec mids ab -n 1 -H "Host: user1.comcast.com"  http://localhost:5000/create_profile
docker-compose exec mids ab -n 1 -H "Host: user1.comcast.com"  http://localhost:5000/menu_search?menu=Mexican
docker-compose exec mids ab -n 1 -H "Host: user1.comcast.com"  http://localhost:5000/menu_search?menu=Lebanese
docker-compose exec mids ab -n 1 -H "Host: user1.comcast.com"  http://localhost:5000/menu_search?menu=Thai
docker-compose exec mids ab -n 1 -H "Host: user1.comcast.com"  http://localhost:5000/menu_search?menu=Pizza
docker-compose exec mids ab -n 1 -H "Host: user1.comcast.com"  http://localhost:5000/order_food?menu=Mexican
docker-compose exec mids ab -n 1 -H "Host: user1.comcast.com"  http://localhost:5000/order_food?menu=Lebanese
docker-compose exec mids ab -n 1 -H "Host: user1.comcast.com"  http://localhost:5000/order_food?menu=Thai
docker-compose exec mids ab -n 1 -H "Host: user1.comcast.com"  http://localhost:5000/order_food?menu=Pizza
docker-compose exec mids ab -n 1 -H "Host: user1.comcast.com"  http://localhost:5000/post_review?review=The+food+was+amazing!
docker-compose exec mids ab -n 1 -H "Host: user1.comcast.com"  http://localhost:5000/post_review?review=Yuck-o-rama!!!
docker-compose exec mids ab -n 1 -H "Host: user1.comcast.com"  http://localhost:5000/post_rating?stars=5
docker-compose exec mids ab -n 1 -H "Host: user1.comcast.com"  http://localhost:5000/post_rating?stars=4
docker-compose exec mids ab -n 1 -H "Host: user1.comcast.com"  http://localhost:5000/post_rating?stars=3
docker-compose exec mids ab -n 1 -H "Host: user1.comcast.com"  http://localhost:5000/post_rating?stars=2
docker-compose exec mids ab -n 1 -H "Host: user1.comcast.com"  http://localhost:5000/post_rating?stars=1
