docker-compose exec mids ab -n 1000 -H "Host: user1.comcast.com"  http://localhost:5000/new_user
docker-compose exec mids ab -n 5827 -H "Host: user1.comcast.com"  http://localhost:5000/login
docker-compose exec mids ab -n 8291 -H "Host: user1.comcast.com"  http://localhost:5000/login0
docker-compose exec mids ab -n 367 -H "Host: user1.comcast.com"  http://localhost:5000/create_profile
docker-compose exec mids ab -n 2125 -H "Host: user1.comcast.com"  http://localhost:5000/menu_search?menu=Mexican
docker-compose exec mids ab -n 3457 -H "Host: user1.comcast.com"  http://localhost:5000/menu_search?menu=Lebanese
docker-compose exec mids ab -n 286 -H "Host: user1.comcast.com"  http://localhost:5000/menu_search?menu=Thai
docker-compose exec mids ab -n 5249 -H "Host: user1.comcast.com"  http://localhost:5000/menu_search?menu=Pizza
docker-compose exec mids ab -n 104 -H "Host: user1.comcast.com"  http://localhost:5000/order_food?menu=Mexican
docker-compose exec mids ab -n 29 -H "Host: user1.comcast.com"  http://localhost:5000/order_food?menu=Lebanese
docker-compose exec mids ab -n 282 -H "Host: user1.comcast.com"  http://localhost:5000/order_food?menu=Thai
docker-compose exec mids ab -n 4311 -H "Host: user1.comcast.com"  http://localhost:5000/order_food?menu=Pizza
docker-compose exec mids ab -n 1098 -H "Host: user1.comcast.com"  http://localhost:5000/post_review?review=The+food+was+amazing!
docker-compose exec mids ab -n 1326 -H "Host: user1.comcast.com"  http://localhost:5000/post_review?review=Yuck-o-rama!!!
docker-compose exec mids ab -n 98 -H "Host: user1.comcast.com"  http://localhost:5000/post_rating?stars=5
docker-compose exec mids ab -n 6243 -H "Host: user1.comcast.com"  http://localhost:5000/post_rating?stars=4
docker-compose exec mids ab -n 1021 -H "Host: user1.comcast.com"  http://localhost:5000/post_rating?stars=3
docker-compose exec mids ab -n 12 -H "Host: user1.comcast.com"  http://localhost:5000/post_rating?stars=2
docker-compose exec mids ab -n 1326 -H "Host: user1.comcast.com"  http://localhost:5000/post_rating?stars=1
